### PR TITLE
Allow user set align origin point for text/image, to make the watermark absulote centered

### PR DESCRIPTION
**Pull request by anyongjin**
In the implementation of the current version, the position of the watermark in the image is aligned with the upper left corner. it is very difficult If we  waant to absolutely center the watermark in the background image. 
So I add the  `setOrigin` method to allow setting the alignment origin of the watermark. When the watermark is printed on the background, it will be placed at the specified position according to the alignment origin.
在当前版本的实现中，水印在图片中的位置是按左上角对齐的，如果需要将水印在背景图片中绝对居中的话，是很难做到的。
所以我新增了setOrigin方法来允许设置水印的对齐原点。将水印防止到背景图片上时，会按对齐原点放置到指定位置上。

### CODE REVIEW

**Comment by anyongjin** [comment]
9ebf1239aacd58f7c73d3117eccae51
ceeb3884808d9152321dc21f2201c61
[androidwm-release.zip](https://github.com/huangyz0918/AndroidWM/files/8159087/androidwm-release.zip)

**Comment by arpanbag001** [comment]
@huangyz0918  This feature is a blocker for us to use this library.

Can you please review and merge the PR if possible?

**Comment by agoodcoolman** [comment]
感谢

**Comment by Comate716** [comment]
> In the implementation of the current version, the position of the watermark in the image is aligned with the upper left corner. it is very difficult If we waant to absolutely center the watermark in the background image. So I add the `setOrigin` method to allow setting the alignment origin of the watermark. When the watermark is printed on the background, it will be placed at the specified position according to the alignment origin. 在当前版本的实现中，水印在图片中的位置是按左上角对齐的，如果需要将水印在背景图片中绝对居中的话，是很难做到的。 所以我新增了setOrigin方法来允许设置水印的对齐原点。将水印防止到背景图片上时，会按对齐原点放置到指定位置上。

非常感谢 太棒了 解决了我的问题

**Pull request merged**
